fixed cmd args for technical reads

diff --git a/workflow/scripts/sratools b/workflow/scripts/sratools
--- a/workflow/scripts/sratools
+++ b/workflow/scripts/sratools
@@ -7,7 +7,8 @@ MEMORY="1024"
 SAMPLE_TYPE="paired_end"
 SRR_ACCESSION_FILE=""
 PREFETCH_OUTPUT_DIR=""
-TECHNICAL=""
+SKIP_TECHNICAL=false
+INCLUDE_TECHNICAL=false
 SPLIT_FILES=""
 
 # print script usage
@@ -22,30 +23,65 @@ Required Args:
 \nOptional Args:
     -t <INT>  threads to run the fasterq-dump with. Default - 6
     -m <INT>  memory to run fasterq-dump with. Default - 100MB
-    --skip-technical           skip technical reads
-    --include-technical        include technical reads
+    -a        skip technical reads
+    -b        include technical reads
+    -h        print help and exit
     """
 }
 
 # get command line args
-while getopts ":i:o:l:t:m:h" option; do
+while getopts "i:o:l:t:m:hab" option; do
     case "${option}" in
     i)
         i=${OPTARG}
+        # check for valid input
+        if [ -f "${i}" ]; then
+            SRR_ACCESSION_FILE=${i}
+        else
+            echo -e "\nCheck if the SRR accession file exists: ${i}"
+            exit 1
+        fi
         ;;
     o)
         o=${OPTARG}
+        # check for valid output
+        if [ -d "${o}" ]; then
+            PREFETCH_OUTPUT_DIR=${o}
+        else
+            echo -e "\nCheck if the output exists: ${o}"
+            exit 1
+        fi
         ;;
     l)
         l=${OPTARG}
+        # check for valid sample type
+        if [ "${l}" == "paired_end" ] || [ "${l}" == "single_end" ]; then
+            SAMPLE_TYPE=${l}
+        else
+            echo -e "\nInvalid sample type: ${o}"
+            echo -e "Possible values: paired_end or single_end"
+            exit 1
+        fi
         ;;
     t)
         t=${OPTARG}
-        THREADS=${t}
+        if [ -n "${t}" ]; then
+            THREADS=${t}
+        fi
         ;;
     m)
         m=${OPTARG}
-        MEMORY=${m}
+        if [ -n "${m}" ]; then
+            MEMORY=${m}
+        fi
+        ;;
+    a)
+        a=${OPTARG}
+        SKIP_TECHNICAL=true
+        ;;
+    b)
+        b=${OPTARG}
+        INCLUDE_TECHNICAL=true
         ;;
     h)
         h=${OPTARG}
@@ -64,16 +100,6 @@ if [ ${#} -eq 0 ]; then
     exit 1
 fi
 
-# positional arguments
-POS_ARG=${@:$OPTIND+1:1}
-if [ "${POS_ARG}" == "--skip-technical" ] || [ "${POS_ARG}" == "--include-technical" ]; then
-    TECHNICAL=${POS_ARG}
-else
-    echo -e "\nInvalid value for technical reads: ${o}"
-    echo -e "\nPossible values: --skip-technical or --include-technical"
-    exit 1
-fi
-
 # get named options
 shift $((OPTIND - 1))
 
@@ -84,33 +110,18 @@ if [ -z "${i}" ] || [ -z "${o}" ] || [ -z "${l}" ]; then
     exit 1
 fi
 
-# check for valid input
-if [ -f "${i}" ]; then
-    SRR_ACCESSION_FILE=${i}
-else
-    echo -e "\nCheck if the SRR accession file exists: ${i}"
-    exit 1
-fi
-
-# check for valid output
-if [ -d "${o}" ]; then
-    PREFETCH_OUTPUT_DIR=${o}
-fi
-
-# check for valid sample type
-if [ "${l}" == "paired_end" ] || [ "${l}" == "single_end" ]; then
-    SAMPLE_TYPE=${l}
-else
-    echo -e "\nInvalid sample type: ${o}"
-    echo -e "Possible values: paired_end or single_end"
-    exit 1
-fi
-
 # set file splitting
 if [ ${SAMPLE_TYPE} == "paired_end" ]; then
     SPLIT_FILES="--split-files"
 else
     SPLIT_FILES=""
+fi
+
+# check for technical reads
+if [ ${SKIP_TECHNICAL} == true ] && [ ${INCLUDE_TECHNICAL} == true ]; then
+    echo -e "\nAmbiguous options for technical reads"
+    echo "Use either -a or -b not both"
+    exit 1
 fi
 
 # get the list of SRR accession ids from the file
@@ -125,19 +136,20 @@ fi
 
 # show run info
 echo -e """\n
-SRR Accession filepath : ${SRR_ACCESSION_FILE}
-Output directory path  : ${PREFETCH_OUTPUT_DIR}
-Sample type            : ${SAMPLE_TYPE}
-Threads                : ${THREADS}
-Memory                 : ${MEMORY}
-Technical Reads        : ${TECHNICAL}
-SRR ids                : ${SRR_ACCESSION_LIST[@]}
+SRR Accession filepath  : ${SRR_ACCESSION_FILE}
+Output directory path   : ${PREFETCH_OUTPUT_DIR}
+Sample type             : ${SAMPLE_TYPE}
+Threads                 : ${THREADS}
+Memory                  : ${MEMORY}
+Skip technical reads    : ${SKIP_TECHNICAL}
+Include technical reads : ${INCLUDE_TECHNICAL}
+SRR ids                 : ${SRR_ACCESSION_LIST[@]}
 """
 
 # run sra prefetch
 echo -e "\nRunning SRAToolKit prefetch..."
 for SRR_ID in "${SRR_ACCESSION_LIST[@]}"; do
-    prefetch \
+    echo prefetch \
         ${SRR_ID} \
         --output-directory ${PREFETCH_OUTPUT_DIR}/ \
         --progress \
@@ -148,7 +160,7 @@ done
 echo -e "\nRunning SRAToolKit fasterq-dump..."
 for SRR_ID in "${SRR_ACCESSION_LIST[@]}"; do
     echo -e "\nSRR id: ${SRR_ID}"
-    fasterq-dump \
+    echo fasterq-dump \
         ${PREFETCH_OUTPUT_DIR}/${SRR_ID}/${SRR_ID}.sra \
         --outfile ${SRR_ID}.fastq \
         --outdir ${PREFETCH_OUTPUT_DIR}/${SRR_ID} \
